### ISSUE TITLE
抱歉打扰啦~如果没有nativePC文件夹怎么办

### ISSUE THREAD

**Issue by MindsculptorX** [HalcyonAlcedo/MHW-Weaponeditor#2]
我的MHW里面有没有整个nativePC文件夹
所以我自己创建了\nativePC\common\equip\
并把自己新建的w_sword.wp_dat放进去
进入游戏后没有任何变化

是哪里没有作对咩
请问有什么解决方法咩

**Comment by HalcyonAlcedo** [comment]
没有文件夹得新建，新建没效果估计是建错了
